### ISSUE TITLE
HGSS bad berries 

### ISSUE THREAD

**Issue by davidhouweling** [champred/UPR-Android#2]
Hey, is the UI missing for turning off bad berries?

I've heard people like Cali and Lig say they turn it off but I don't see it in the settings.

Could this be included and settings strings updated?

**Comment by champred** [comment]
Hi, sorry for letting this go unnoticed for so long! Unfortunately there isn't a good way to get around the berries besides downloading an older version of the app. I've been thinking about possibly making a custom item ban list, but haven't gotten around to it yet.

**Comment by champred** [comment]
https://github.com/champred/UPR-Android/blob/8f0e7a908701015f4e2c9a2ac780a6b9a4933582/upr/src/com/dabomstew/pkrandom/constants/Gen4Constants.java#L923

Could be possible to have a flag that toggles this between the current value and the old value of 54.

**Comment by champred** [comment]
Latest release has added a separate version with the berries disabled. I may look into finding a way to turn it into a setting. Unfortunately I couldn't really change the settings strings as that would break compatibility. Feedback would be appreciated!

**Comment by champred** [comment]
I've now added a checkbox to allow the berries. This should hopefully be easier to use than downloading a different version of the app, but since it isn't saved as a part of the settings it will need to be manually unchecked after you load the ROM.

![image](https://github.com/champred/UPR-Android/assets/46391895/f8acb3ba-da94-48fe-9fbb-80df4c259b8e)
