### ISSUE TITLE
Special characters such as the "é" in "Pokémon" are incorrect

### ISSUE THREAD

**Issue by fishcu** [champred/UPR-Android#7]
When randomizing a HGSS ROM, the resulting ROM will have special characters replaced by the wrong characters, for example the "é" in "Pokémon", or the " ' " in "you'll".

I have done the patching with the latest released version v0.3.3 and with a clean HG ROM on an Android 12 device.

I have attached two screenshots that show the issue.

![image](https://github.com/champred/UPR-Android/assets/25356186/c7c498fa-6b40-4e49-85b6-f29e259491db)
![image](https://github.com/champred/UPR-Android/assets/25356186/8710b30f-a5f4-461f-9385-4c6e07f170a6)

**Comment by fishcu** [comment]
As another data point, FireRed behaves in the same fashion.

Interestingly, the wrong character mapping is the same, i.e., é => [nothing] and ' => â.

![image](https://github.com/champred/UPR-Android/assets/25356186/c6bf11c7-c0c3-42ce-b0be-08bb033e235b)

**Comment by champred** [comment]
It appears that Android replaces special characters in the source code with escape sequences. Tentatively I have hardcoded those escape sequences in the characters tables. This could potentially affect more special characters though. Please check both gen 3&4 and report back.

**Comment by champred** [comment]
As a more permanent measure I have added the escape sequences as alternative entries to the maps used for associating strings with corresponding bytes in the ROM code for gens 1-4. Honestly I'm not sure why this even works. Also I don't know if this would affect gen 5 as well. Keeping the issue open for the time being.

**Comment by champred** [comment]
After doing more research it seems that é gets replaced with the bytes `C3 A9` when compiling on Windows. This makes no sense considering the character byte is `E9` in both UTF-8 and Windows-1252.

Similarly the apostrophe character `2019` is replaced with `E2 20AC 2122` which at least makes more sense considering it's multiple bytes. It turns out that `E2` is â which is why that shows up.

To fix this I set the encoding option to be UTF-8 in the Gradle build script. The unicode escape decoding might be completely unnecessary. Although strangely enough it still appears to give the correct results even with the incorrect escapes which is even more confusing.
